### ISSUE TITLE
Public API should return serializable values

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-meta-feeds#15]
There are a couple of problems with the public API, @arj03 :

## Can't use over ssb-client

The `getOrCreate(cb)` returns a `mf` object which has the method `getOrCreateFeed()`. This works when calling the API from the sbot process, but wouldn't work over `ssb-client`, because the method is not serializable over muxrpc.

## Can't create metafeed under metafeed

For the use case of creating *root meta feed* => *indexes meta feed* => *index feed*, I don't think we currently support creating it, because `ssb.metafeeds.metafeed.getOrCreate()` returns the *root meta feed* which has the method `getOrCreateFeed()` which can create the *indexes meta feed* but it won't come with another method, so we don't have a way of creating *index feed* as a child of *indexes*.

## Unclear what is internal and external APIs

It would be good to not expose low-level APIs, but to just provide the methods that are needed for managing meta feeds on a high level.

## Suggestion

I suggest we change the public API to (this is open to feedback!):

```diff
-sbot.metafeeds.keys.generateSeed()
-sbot.metafeeds.keys.deriveFeedKeyFromSeed(seed, label, feedformat)
-sbot.metafeeds.messages.addExistingFeed(metafeedKeys, previous, feedpurpose, feedKeys, metadata)
-sbot.metafeeds.messages.addNewFeed(metafeedKeys, previous, feedpurpose, seed, feedformat, metadata)
-sbot.metafeeds.messages.tombstoneFeed(metafeedKeys, previous, feedKeys, reason, cb)
-sbot.metafeeds.messages.generateAnnounceMsg(metafeedKeys, cb)
-sbot.metafeeds.messages.generateSeedSaveMsg(metafeedId, mainfeedId, seed)
-sbot.metafeeds.query.getSeed(cb)
-sbot.metafeeds.query.getAnnounce(cb)
-sbot.metafeeds.query.getMetadata(feedId, cb)
-sbot.metafeeds.query.hydrate(feedId, seed, cb)
-sbot.metafeeds.metafeed.getOrCreate(cb)
+sbot.metafeeds.loadOrCreate(opts, cb)
```

(`getOrCreate` renamed to `loadOrCreate` just to match the naming used in ssb-keys: `ssbKeys.loadOrCreate`)

Where `opts` would have all the arguments we need, some of them are anyway optional like `metadata`.

To create the root meta feed (linked to `main`):

```js
sbot.metafeeds.loadOrCreate({ parent: null }, (err, mf) =>{
  console.log(mf);
  // {
  //   seed,
  //   keys,
  //   feeds,
  //   tombstoned,
  //   latest,
  // }
})
```

To create a sub meta feed (such as `indexes`):

```js
sbot.metafeeds.loadOrCreate({
  parent: mf,
  purpose: 'indexes', 
  format: 'bendy butt',
  // etc
}, cb)
```

And this `opts` would also have a way of specifying the `ssb-ql-1` object, so that we *get-or-create* the index feed identified by its query object.

-----

UPDATE: oh, instead of looking for a feed that has `feed.feedpurpose === feedpurpose`, we could just let `opts` pass a JITDB operator and this could apply on any field!

For instance, to create sub meta feed like `indexes`:

```js
sbot.metafeeds.loadOrCreate({ 
  parent: mf, 
  query: and(slowEqual('value.content.feedpurpose', 'indexes')),
}, cb)
```

To create an index feed under `indexesMF`:

```js
sbot.metafeeds.loadOrCreate({
  parent: indexesMF,
  query: and(
    slowEqual('value.content.feedpurpose', 'index'),
    slowEqual('value.content.querylang', 'ssb-ql-1'),
    slowEqual('value.content.query', JSON.parse(myIndexQuery))
  )
}, cb)
```

**Comment by staltz** [comment]
> Can't use over ssb-client

I realize this is not the biggest problem, we also [cannot use ssb-db2 over ssb-client, yet](https://github.com/ssb-ngi-pointer/ssb-db2/issues/89).

So that in mind we could use a simpler API, that instead of taking JITDB operations, just takes a `find` function and a `create` function:

```js
sbot.metafeeds.loadOrCreate({
  parent: indexesMF,
  find: (feed) => 
    feed.feedpurpose === 'index' && 
    feed.querylang === 'ssb-ql-1' && 
    isSameQL1(feed.query, theIndexQueryIWant),
  create, // instructions to create the feed if `find` didn't encounter one
}, cb)
```

**Comment by arj03** [comment]
I like that last example better with just a find. I don't think we need to create indexes for these query other than what we already have. I'm guessing these will make sure `sbot.metafeeds.metafeed.getOrCreate` is called so that the mf is available before we start doing anything. Also I think we need at least some query methods, like sometimes you might just want to know if a feed is there or not. That should be able to work with any metafeed, not just your own, so I'm not sure if that should live in this library or another module.

**Comment by staltz** [comment]
We just had a call, here's our conclusions:

We might need to get all matched feeds for a given `find` function, not just one.

We should split this monolith `loadOrCreate` API into smaller ones, such as (draft):

- `sbot.metafeeds.filter(parent, pickerFn, cb)` similar to Array.prototype.filter, plural results
- `sbot.metafeeds.find(parent, pickerFn, cb)` similar to Array.prototype.find, singular result
- `sbot.metafeeds.create(parent, details, cb)`
- `sbot.metafeeds.findOrCreate(parent, pickerFn, details, cb)` as a shortcut for the two above

When looking for index feeds, the previously mentioned `isSameQL1` function might be tricky to implement, because we need to match `and(FOOD, SPICY)` with `and(SPICY, FOOD)`, and originally the `query` field in `msg.value.content` is a string, not an object, so we may have to parse the `query` JSON so to do deep equality, **or** we could compare the strings directly, if and only if we specify a canonical stringification of `ssb-ql-1` queries. 

Question: are there easy JS modules out there that do "sorted JSON.stringify" to always have lexicographically sorted fields? 

Another question: what if a canonical format is not enough? For example, consider `and(FOOD, and(SPICY, MEXICAN))`. It is functionally equivalent to `and(FOOD, SPICY, MEXICAN)` but a canonical (e.g. lexicographic sorted) stringification of those are, respectively, `and(FOOD, and(MEXICAN, SPICY))` and `and(FOOD, MEXICAN, SPICY)` which are **not** the same strings.
