### ISSUE TITLE
Fix subfeed() db2 operator to account for SSB URIs

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-meta-feeds#38]
This line: 

https://github.com/ssb-ngi-pointer/ssb-meta-feeds/blob/5b8b331c26f49ba8101913f8df4e8cafb33de8e9/query.js#L30

Should not use prefixOffset=1 because not all `subfeeds` are classic, some are meta feeds, e.g. `root` => `indexes` => `index`, the `indexes` will be a `subfeed` message on the `root`, and `indexes` has an SSB URI for bendy butt.

We should apply a similar technique as https://github.com/ssb-ngi-pointer/ssb-db2/pull/255/commits/8abc0a57499d4d73abf18af50d12d6c9232ab4a4

**Comment by staltz** [comment]
cc @arj03 @mycognosist I have my hands full at the moment (with `ssb-meta-feeds-rpc` and replication-scheduler and the new "A2A" spec discussed at Svendsolar) so if any of you get some free time at some point, this one should be simple to fix.

**Comment by arj03** [comment]
@mycognosist ? I'm busy with ebt changes :)

**Comment by mycognosist** [comment]
Sure thing, I'll take a look.

**Comment by mycognosist** [comment]
Fixed in https://github.com/ssb-ngi-pointer/ssb-meta-feeds/pull/39
