### ISSUE TITLE
Convinience functions

### ISSUE THREAD

**Issue by arj03** [ssb-ngi-pointer/ssb-meta-feeds#4]
- ~get latest state of a meta feed~
- get meta feed given a main feed
- get the latest state of meta feeds for a number of main feeds
- maybe a way to look for specific feeds, like index feeds?

**Comment by staltz** [comment]
@arj03 I think PR #17 would cover these use cases, at least (for sure):

> * get meta feed given a main feed
> * maybe a way to look for specific feeds, like index feeds?

**Comment by arj03** [comment]
Agree :)
