### ISSUE TITLE
Match key derivation implementation with Go

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-meta-feeds#8]
I tried to use a seed from Go

https://github.com/ssb-ngi-pointer/go-metafeed/blob/e2d13ec3b587c204bf5e22aa3d6f581418b9e5b8/internal/vectors/gen_good_test.go#L33

(the same one that is in the test vector JSON in ssb-bendy-butt tests), and in this module it didn't generate the same SSB ID. I fiddled with this module's implementation until these changes worked:

```diff
+//                                             label = 'metafeed'
 exports.deriveFeedKeyFromSeed = function(seed, label, feedformat) {
   if (!label) throw new Error("label was not supplied")
   
-  const salt = 'ssb'
+  const salt = ''
 
   const hash = 'SHA-256'
   const ed25519_length = 32
 
-  const derived_seed = hkdf(seed, ed25519_length, { salt, info: 'ssb-meta-feed-seed-v1:' + label, hash })
+  const derived_seed = hkdf(seed, ed25519_length, { salt, info: 'ssb-meta-feeds-v1:' + label, hash })
   const keys = ssbKeys.generate("ed25519", derived_seed)
   if (feedformat === 'bendy butt')
     keys.id = keys.id.replace("ed25519", "bbfeed-v1")

   return keys
 }
```

See how Go does key derivation:

https://github.com/ssb-ngi-pointer/go-metafeed/blob/e2d13ec3b587c204bf5e22aa3d6f581418b9e5b8/metakeys/generate.go

I don't know which implementation is incorrect, but I know that one of these needs to be updated.

**Comment by arj03** [comment]
I'll have a look at this tonight

**Comment by arj03** [comment]
The JS implementation should be correct. Salt and info are defined [here](https://github.com/ssb-ngi-pointer/ssb-meta-feed-spec#existing-ssb-identity) and [here](https://github.com/ssb-ngi-pointer/ssb-meta-feed-spec#new-ssb-identity).

There are some other problems in this module though, let me address those in a separate PR.
